[theme]
primaryColor       = "#3525CD"
backgroundColor    = "#F8F9FA"
secondaryBackgroundColor = "#F3F4F5"
textColor          = "#191C1D"
font               = "sans serif"

[browser]
gatherUsageStats = false
